apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-dashboard
  template:
    metadata:
      labels:
        app: devops-dashboard
    spec:
      containers:
      - name: dashboard
        image: kaushal13x/devops-dashboard:v1
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "v1.0"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10